"""Initial schema with indexes

Revision ID: e3507fe85222
Revises: 
Create Date: 2026-02-20 09:08:21.128257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3507fe85222'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('risk_rating', sa.String(), nullable=True),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index('idx_client_region_risk', 'clients', ['region', 'risk_rating'], unique=False)
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_region'), 'clients', ['region'], unique=False)
    op.create_index(op.f('ix_clients_risk_rating'), 'clients', ['risk_rating'], unique=False)
    op.create_table('operations',
    sa.Column('operation_id', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('operation_id')
    )
    op.create_index('idx_operation_region_status', 'operations', ['region', 'status'], unique=False)
    op.create_index(op.f('ix_operations_operation_id'), 'operations', ['operation_id'], unique=False)
    op.create_index(op.f('ix_operations_region'), 'operations', ['region'], unique=False)
    op.create_index(op.f('ix_operations_status'), 'operations', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('sla_breach_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('idx_transaction_client_date', 'transactions', ['client_id', 'transaction_date'], unique=False)
    op.create_index('idx_transaction_timestamp', 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_client_id'), 'transactions', ['client_id'], unique=False)
    op.create_index(op.f('ix_transactions_sla_breach_flag'), 'transactions', ['sla_breach_flag'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_sla_breach_flag'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_client_id'), table_name='transactions')
    op.drop_index('idx_transaction_timestamp', table_name='transactions')
    op.drop_index('idx_transaction_client_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_operations_status'), table_name='operations')
    op.drop_index(op.f('ix_operations_region'), table_name='operations')
    op.drop_index(op.f('ix_operations_operation_id'), table_name='operations')
    op.drop_index('idx_operation_region_status', table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_clients_risk_rating'), table_name='clients')
    op.drop_index(op.f('ix_clients_region'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_index('idx_client_region_risk', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
